:toc: macro

Back to the link:Home[Back to the DOSBox-X Wiki Welcome page]

# Setting up printing in DOSBox-X

toc::[]

## Overview
DOSBox-X has support for printing to either a real parallel printer, or to a text, PNG, PostScript or BMP file.

Printer options in the config are split over two config options, ```[parallel]``` and ```[printer]```.

The Virtual Printer emulates a color dot-matrix printer that follows the ESC/P2 printing standard.

Example of printers that typically work fine:

* Epson LQ-800
* IBM Pro Printer

**Features:**

* Many of the ESC/P and ESC/P2 instructions supported
* Graphics printing for 24-pin and 48-pin modes supported, up to 360dpi
* Color output, use "Generic ESC/P 24pin wide" printer on Windows 3.11 or "Epson SQ 860" on Win95
* Data can be output as Windows bitmap, PNG file, Postscript file, or sent to a Windows
* Some older non-conflicting IBM control codes are supported

**Limitations:**

* Windows printer output in black & white only
* Not all ESC/P commands are supported, like custom fonts
* The default font (courier.ttf)
* Due to overexact graphics emulation 360dpi printing from Windows (guest) graphics rastering might not look as expected
* When set to use a Windows printer, the printer dialog will only show up once at start
* Country code setup and other configuration buttons found on a printer are not available, this may be overcome by sending special ESC/P commands to the printer before printing

### [parallel] section options
This section lists the available configuration options for the ```[parallel]``` section that DOSBox-X provides.

#### parallel1
* Default value: disabled
* Possible values: disabled, reallpt, file, printer, disney

This enables an emulated LPT1 port on IO base address 0x378.

....
Additional parameters must be in the same line in the form of
#              parameter:value.
#                for reallpt:
#                Windows:
#                  realbase (the base address of your real parallel port).
#                    Default: 378
#                  ecpbase (base address of the ECP registers, optional).
#                Linux: realport (the parallel port device i.e. /dev/parport0).
#                for file:
#                  dev:<devname> (i.e. dev:lpt1) to forward data to a device,
#                  or append:<file> appends data to the specified file.
#                  Without the above parameters data is written to files in the capture dir.
#                  Additional parameters: timeout:<milliseconds> = how long to wait before
#                  closing the file on inactivity (default:500), addFF to add a formfeed when
#                  closing, addLF to add a linefeed if the app doesn't, cp:<codepage number>
#                  to perform codepage translation, i.e. cp:437
#                for printer:
#                  printer still has it's own configuration section above.
....
* "disabled" disables LPT1 in DOSBox-X

#### parallel2
* Default value: disabled
* Possible values: disabled, reallpt, file, printer, disney

This enables an emulated LPT1 port on IO base address 0x278.

#### parallel3
* Default value: disabled
* Possible values: disabled, reallpt, file, printer, disney

#### dongle
* Default value: false
* Possible values: false, true

### [printer] section options
This section lists the available configuration options for the ```[printer]``` section that DOSBox-X provides.

Only one printer can be emulated, and it can only be connected to a single virtual parallel port. It is also necessary for the virtual printer to configure TrueType fonts.

#### printer
* Default value: false
* Possible values: true, false

Enables or disables printer emulation.

#### dpi
* Default value: 360
* Possible values:

#### width
* Default value: 85
* Possible values:

Width of paper in 1/10 inch. The default 85 corresponds to 8.5".

Example of standard paper sizes in portrait orientation:

* Letter = 85 (default)
* Legal = 85
* A3 = 116 (297mm = 11.69 inches)
* A4 = 82 (210mm = 8.27 inches)
* A5 = 58 (148mm = 5.83 inches)

#### height
* Default value: 110
* Possible values:

Height of paper in 1/10 inch. The default 110 corresponds to 11.0".

Example of standard paper sizes in portrait orientation:

* Letter = 110 (default)
* Legal = 140
* A3 = 165 (420mm = 16.53 inches)
* A4 = 116 (297mm = 11.69 inches)
* A5 = 82 (210mm = 8.27 inches)

#### printoutput
* Default value: png
* Possible values: png, ps, bmp

#### multipage
* Default value: false
* Possible values: true, false

Adds all pages to one PostScript file or printer job until CTRL-F2 is pressed.

#### docpath
* Default value: .

The path where the output files are stored. Defaults to the current working directory.

#### timeout
* Default value: 0
* Possible values:

Timeout (in milliseconds).

If nonzero: the time the page will be ejected automatically when no more data arrives at the printer.

# Setting up fonts for the emulated printer
The emulated printer requires TrueType fonts to be setup. At a minimum you need ```courier.ttf```.

Note: this is an area that needs improvement as DOSBox-X could try to use the default system fonts...

## Windows host
In the directory where your dosbox-x.exe is located, create a directory FONTS. Now copy from your C:\Windows\Fonts directory the following files to the FONTS directory and rename them.

|===
|Original filename and location|New filename and location

|C:\Windows\Fonts\cour.ttf|FONTS\courier.ttf
|C:\Windows\Fonts\times.ttf|FONTS\roman.ttf
|C:\Windows\Fonts\arial.ttf|FONTS\sansserif.ttf
|Download Ocraext.ttf|FONTS\ocra.ttf
|C:\Windows\Fonts\freescpt.ttf|FONTS\script.ttf
|===

## Linux host
|===
|Original filename and location|New filename and location

|/usr/share/fonts/liberation-mono/LiberationMono-Regular.ttf|FONTS\courier.ttf
|/usr/share/fonts/liberation-serif/LiberationSerif-Regular.ttf|FONTS\roman.ttf
|/usr/share/fonts/liberation-sans/LiberationSans-Regular.ttf|FONTS\sansserif.ttf
|Download Ocraext.ttf|FONTS\ocra.ttf
||FONTS\script.ttf
|===

# Example: Print to text file
In this example the output of DOS commands is simply redirected to the virtual LPT port, which in turn will be redirected to a text file.

Setup a DOSBox-X config file with the following lines:
....
[dosbox]
captures=capture

[parallel]
parallel1=file
....
No ```[printer]``` section is needed for this example.

Now start DOSBox-X, and type the following command:
....
DIR > LPT1
....

This will cause a ```capture\dosbox_000.prt``` ASCII text file to be created.
The exact save location is dependent on the ```captures=``` setting in the ```[dosbox]``` section.

You can also use this in most DOS programs, by selecting a generic text printer, or in Windows 3.x, 95 or 98 by selecting the "Generic / Text Only" printer.

Note: If you booted real DOS, or Windows 9x in DOSBox-X the filename will be ```guest os_000.prt``` instead.


# Example: Printing to a real parallel printer

These examples are untested due to lack of suitable hardware. Confirmation is requested.

## Windows host
This assumes you PC still has a printer port integrated on the systemboard, or a legacy ISA printer adapter. It reportedly will not work with USB printer adapters or PCI printer port adapters.

Make sure your dosbox-x config file contains the statements:
....
[parallel]
parallel1=file dev:lpt1
....

Alternatively you can try to set it up as follows, but this reportedly only works if your host is running Windows 9x, or with later Windows versions by installing "PortTalk"

....
[parallel]
paralel1=reallpt directlpt:378
....

Another alternative is to install link:http://www.dosprn.com/[DOSPRN], a Shareware application that specifically lists DOSBox-X as supported for printing to any printer configured on the Windows host system.

## Linux host

First you need to give your Linux user access to the /dev/parport0 device, otherwise you will get permission denied errors.
Replace "username" with your Linux username.

....
sudo usermod -a -G lp username
....

Now, similar to the Windows instructions, try the following:

Make sure your dosbox-x config file contains the statements:
....
[parallel]
parallel1=reallpt realport:/dev/parport0
....

This has been confirmed to work. Alternatively you can try to set it up as follows:

....
[parallel]
parallel1=file dev:/dev/parport0
....

But while this method seems to work on Windows, it does not seem to work properly on Linux.

# Example: Printing to a real printer

## Windows host
This method will cause a Windows print dialog to appear on the host, and you can print to any printer configured on the host, including print to PDF.

This method requires that you have first completed the FONT installation step above.

Make sure your dosbox-x config file contains the statements:
....
[parallel]
parallel1=printer

[printer]
printer=true
printoutput=printer
timeout=1000
....
