:toc: macro

Back to the link:Home[Back to the DOSBox-X Wiki Welcome page]

# Managing images files

toc::[]

# Overview
DOSBox-X supports a three types of image files;

* Diskette images
* Harddisk images
* CD-ROM or DVD images

# Diskette images
DOSbox-X supports diskette images in MFM sector image format.
These commonly have an extension of IMG or IMA, and sometimes DSK.
The IMG extension is also used for harddisk images, so there can be some confusion.
Files with the extension IMA are automatically treated as diskette images.

NOTE: There is no support for any type of copy protected diskettes. Any programs on copy protected diskettes need to be "cracked" to remove the copy protection before they can be used by DOSBox-X.

Some examples of diskette image files that DOSBox-X **does not** support:

* IBM DSKF (.DSK)
* IBM XDF (.XDF)
* ImageDisk (.IMD)
* Interchangeable Preservation Format (.IPF)
* KryoFlux Stream files (.RAW)
* Microsoft DMF (.DMF)
* Teledisk (.TD0)
* Transcopy (.TC)

## Creating diskette images

DOSBox-X has a special built-in ``IMGMAKE`` command with which you can create formatted diskette images from the DOSBox-X command prompt.

example:
....
IMGMAKE disk.ima -t fd_1440
....
This will create a 1.44MB formatted disk image named disk.ima.
The diskette image will appear to have been formatted by MS-DOS 5.0.

NOTE: The filename in this case is not limited to the DOS 8.3 filename length, but rather by your host filesystem.

You can optionally create a diskette image that is not formatted with:
....
IMGMAKE disk.ima -t fd_1440 -nofs
....
NOTE: DOSBox-X has no integrated FORMAT command, so creating diskette images that are not formatted is typically not recommended.

DOSBox-X will automatically assume it is a diskette image if the filename extension is .IMA, or if your mounting on the emulated A: or B: drive.
If this is not the case, you can force a diskette type with the ``-t floppy`` parameter.

Supported diskette sizes options:

|===
|Disk type|Capacity|IMGMAKE option

|5.25" SSDD (8 sector)|160KB|-t fd_160
|5.25" SSDD |180KB|-t fd_180
|5.25" SSDD (10 sector)|200KB|-t fd_200
|5.25" DSDD (8 sector)|320KB|-t fd_320
|5.25" DSDD|360KB|-t fd_360
|5.25" DSDD (10 sector)|400KB|-t fd_400
|5.25" HD|1200KB (1.2MB)|-t fd_1200
|3.5" DSDD (2DD)|720KB|-t fd_720
|3.5" HD|1440KB (1.44MB)|-t fd_1440
|3.5" ED|2880KB (2.88MB)|-t fd_2880
|===

NOTE: the 8-sector formats should be avoided unless your need backward compatibility with DOS 1.x.

## Mounting diskette images
Mounting a diskette image in DOSBox-X is typically as simple as

....
imgmount a disk.ima
....
This is equivalent to
....
imgmount A: disk.ima
imgmount A: disk.ima -t floppy
....
NOTE: The ``-t floppy`` parameter is only needed with DOSBox-X when the extension is not .IMA, and your wanting to mount a diskette image on drives greater than B:

A diskette image that is not formatted, or has a unsupported filesystem can be mounted as follows:
....
imgmount 0 disk.ima -fs none
....
0 represents drive A: and 1 represents drive B:. The use of 0 or 1 is required if your using the ``-fs none`` flag to mount a diskette image.

### Mounting multiple diskette images
Some DOS programs or games came on multiple diskettes, for this purpose it is possible to mount multiple diskette images on one drive letter and swap between them.
e.g.
....
imgmount a disk1.ima disk2.ima disk3.ima
....
In this example disk1.ima will be immediately usable on A: but disk2.ima will require a disk-swap action.

Disk-swap can be done using either a hot-key combination, or using the menu bar.
The hot-key for Windows is F11+CTRL+D and for other platforms F12+CTRL+D.
Or from the menu you can select "DOS" followed by "Swap floppy".

Unless you have a console open with the log, there is no visual indication of which diskette image is currently mounted.

### Write protecting diskette images
By default diskette images are mounted read-write.
You can make a diskette image read-only (write protected) by attaching the ``:`` prefix to the filename.
e.g.
....
imgmount a :disk.ima
....

This can also be used when mounting multiple diskette images.
....
imgmount a :disk1.ima :disk2.ima :disk3.ima userdisk.ima
....
In the above example, the first 3 disks are read-only, but the last one is read-write.

## Unmounting diskette images
Diskette images can be unmounted using the ``-u`` flag. e.g.
....
imgmount a -u
....
You can also unmount using the ``MOUNT`` command.
....
mount a -u
....
It is also possible to unmount the currently mounted image, and mount a new image in one step.
....
imgmount a disk2.ima -u
....
This will cause the currently mounted disk image (if any) to be unmounted, and disk2.ima to be mounted instead.

Alternatively you can unmount a diskette from the DOSBox-X menu bar by selecting "Drive", followed by the drive letter and "Unmount".

## Boot from a diskette image
You can either mount a disk image first and then boot from it:
....
imgmount a dos.ima
boot a:
....
NOTE: DOSBox-X supports the ``-L`` parameter for the ``BOOT`` command for backward compatibility with vanilla DOSBox, or other forks, but the parameter is not required with DOSBox-X to boot from a drive letter.

Or you can boot directly from a disk as such:
....
boot dos.ima
....

TIP: Multiple image files can be specified with either the ``IMGMOUNT`` or ``BOOT`` commands, in case you have a multi-disk install program.
Image files can be made read-only by prefixing the filename with a column character (``:``).

CAUTION: DOSBox-X will attempt to boot from a diskette, even if it is not bootable. This is needed to support early PC-Booter games.

## Using diskette images in Linux
WARNING: You should never mount a disk image simultaneously in both DOSBox-X and in Linux, as that can cause corruption of files or the filesystem on the diskette image.

### Gnome Disk Image Mounter
If your using the Gnome desktop environment, you can open .IMG disks with the "Disk Image Mounter". Simply right click on the file, and select 'Open with Disk Image Mounter' and the file will be mounted in the Gnome file manager.

The first time you want to open .IMA files, you need to right-click and choose "Open With Other Application", and then click on "View All Applications" and choose "Disk Image Mounter" from the list.
The next time you want to open a .IMA file, the option will be available directly from the right-click menu.

Disks can be unmounted from the Gnome file manager by clicking the unmount button next to the volume name.

Disk images can also be mounted from the Linux Terminal using:
....
gnome-disk-image-mounter disk.ima
....

### Mounting a diskette image from the shell
The more traditional Linux method of mounting diskette image files from a Linux terminal.
This method requires sudo access.

....
sudo mount -o loop,uid=$UID disk.ima /mnt
....
The above command will cause disk.ima to be mounted under /mnt.

### GNU mtools
GNU mtools is an optional package you can install to interact with DOS disks or disk images.
It provides various commands which can be used to interact with DOS diskette images without having to mount them.

A subset of commands provided by mtools:
|===
|Command|DOS equivalent |Note

|mattrib|ATTRIB|View and change file attributes
|mcopy|COPY|Copy files
|mdel|DEL|Delete files
|mdeltree|DELTREE|Delete directory tree
|mdir|DIR|List directory contents
|mdu|-|Disk Usage
|minfo|-|Info about the disk
|mlabel|LABEL|Label disk
|mmd|MD / MKDIR|Make directory
|mmove|MOVE|Move file or directory
|mrd|RD / RMDIR|Remove directory
|mren|REN / RENAME|Rename file or directory
|mtype|-|unix type command
|===


#### List contents of a diskette image

This will list the contents of the root directory of the diskette image, similar to the DOS DIR command.
....
mdir -i disk.ima
....

Assuming the diskette image has a directory named DOS, the contents can be listed as
....
mdir -i disk.ima ::dos
....

#### Copy file into a diskette image
This command will copy the file hello.txt into the root directory of the disk image.
....
mcopy -i disk.ima hello.txt ::
....

This command will copy the file hello.txt into the DOS directory of the disk image.
....
mcopy -i disk.ima hello.txt ::DOS
....

#### Copy file(s) out of a diskette image
This command will copy the file hello.txt out of the root of the diskette image, to the current directory (.)
....
mcopy -i disk.ima ::hello.txt .
....

Or if you want to copy all files, including sub-directories, from the diskette image to the directory tmp
....
mkdir tmp
mcopy -s -i disk.ima :: tmp
....

## Using diskette images in Windows
WARNING: You should never mount a disk image simultaneously in both DOSBox-X and in Windows, as that can cause corruption of files or the filesystem on the diskette image.

Windows 8 and newer has integrated support for mounting image files, and will offer the "Mount" option when you right-click a .IMG file.
Unfortunately this support is incompatible with the image files used by DOSBox-X, and the mount will fail.

However, several 3rd party tools are available which can open the diskette image files:

* link:https://www.7-zip.org/[7-Zip]
* link:http://www.winimage.com/winimage.htm[WinImage]
* link:https://www.win-rar.com/[WinRAR]
* link:https://www.winzip.com/[WinZIP]

# Harddisk images
DOSbox-X supports harddisk images in MFM sector image format, or in QCOW2 format.

Creating and accessing harddisk images is very similar to diskette images, with the exception that they also contain partitions and they may contain other filesystems.

## Creating harddisk images
DOSBox-X has a special built-in ``IMGMAKE`` command with which you can create partitioned and formatted harddisk images from the DOSBox-X command prompt. ``IMGMAKE`` only creates a single primary DOS partition per harddisk image file.

Harddisk images up to 2GB will appear to have been partitioned and formatted by MS-DOS 5.0 using FAT16.

Harddisk images greater than 2GB, up to 8GB will not be partitioned and formatted. This is because FAT16 only supports partitions up to 2GB, and larger partitions require FAT32 which is not supported by ``IMGMAKE`` at this point.

### Using templates
example:
....
IMGMAKE hdd.img -t hd_520
....
This will create a 520MB partitioned and formatted harddisk image named hdd.img.

NOTE: The filename in this case is not limited to the DOS 8.3 filename length, but rather by your host filesystem.

You can optionally create a harddisk image that is not partitioned and formatted with:
....
IMGMAKE hdd.img -t hd_520 -nofs
....
NOTE: DOSBox-X has no integrated FDISK and FORMAT commands, so creating harddisk images that are not partitioned and formatted is typically not recommended.

Supported harddisk sizes options using templates:

|===
|Disk type|Capacity|CHS|IMGMAKE option

|Seagate ST225|21MB (~ 20.23MB usable)|615,4,17|-t hd_st225
|Seagate ST251|41MB (~ 40.65MB usable)|820,6,17|-t hd_st251
||241MB (~ 240.39MB usable)|489,16,63|-t hd_250
||504MB (~ 503.21MB usable)|1023,16,63|-t hd_520
||2GB (~ 1.96GB usable)|1023,64,63|-t hd_2gig
||4GB|1023,130,63|-t hd_4gig
||8GB|1023,255,63|-t hd_8gig

|===

NOTE: The 4 and 8GB options will not be partitioned and formatted.
This is because disks greater than 2GB cannot be formatted FAT16, and at this time the ``IMGMAKE`` command has no support for FAT32.

### Custom size
Instead of using one of the templates, you can create a custom size harddisk up to 8GB by either specifying the size in MB or CHS geometry.

To create a partitioned and formatted 31MB HDD image:
....
IMGMAKE hdd.img -t hd -size 31
....

The same can be accomplished with the CHS (Cylinders, Heads, Sectors) geometry:
....
IMGMAKE hdd.img -t hd -chs 992,2,32
....
The maximum allowed CHS value is 1023,255,63 which will create a 8GB HDD image.

You can optionally create a harddisk image that is not partitioned and formatted by specifying ``-nofs``:
....
IMGMAKE hdd.img -t hd -size 31 -nofs
....
NOTE: DOSBox-X has no integrated FDISK and FORMAT commands, so creating harddisk images that are not partitioned and formatted is typically not recommended.

## Mounting harddisk images
Mounting a harddisk image in DOSBox-X is typically as simple as

....
imgmount c hdd.img
....
This is equivalent to
....
imgmount C: hdd.img
imgmount C: disk.ima -t hdd
imgmount C: disk.ima -t hdd -fs fat
....
NOTE: The ``-t hdd`` option is only needed with DOSBox-X when mounting a harddisk image on the emulated A: or B: drive, as those are normally reserved for diskettes.
Or when mounting a harddisk image that is not partitioned or formatted, or formatted with an unsupported filesystem in combination with the ``-size`` parameter.
The ``-fs fat`` option should not be needed as the FAT12, FAT16 or FAT32 filesystem types will be automatically detected.

NOTE: If a harddisk image has multiple partitions, you can only access the first partition from the DOSBox-X integrated DOS. When booting real DOS in DOSBox-X, all partitions will be accessible.

A harddisk image that is not formatted, or has an unsupported filesystem can be mounted as follows:
....
imgmount 2 hdd.img -fs none
....
When using the ``-fs none`` option, it is required to use a device ID instead of a drive letter.

|===
|Device ID|Controller option|IDE Controller|Master/Slave

|2|-ide 1m|Primary|Master
|3|-ide 1s|Primary|Slave
|4|-ide 2m|Secondary|Master
|5|-ide 2s|Secondary|Slave
|===

A harddisk image that is also not partitioned needs additional parameters, such as a template or the size in SHC.

Using the original template it was based on:
....
imgmount 2 hdd.img -t hd_4gig -fs none
....

Or using the original SHC it was based on:
....
imgmount 2 hdd.img -t hdd -size 512,32,2,992 -fs none
....

IMPORTANT: The geometry values for the IMGMOUNT command are inversed compared to IMGMAKE.
So instead of specifying the size in CHS order, it needs to be specified in SHC (Sectors, Heads, Cylinders) order.
In addition it needs to be prefixed with the bytes-per-sector, which should always be 512 for now.
So a CHS of 992,2,32 becomes ``-size 512,32,2,992``.

## Unmounting harddisk images
Harddisk images can be unmounted using the ``-u`` flag. e.g.
....
imgmount c -u
....
You can also unmount using the ``MOUNT`` command.
....
mount c -u
....
It is also possible to unmount the currently mounted image, and mount a new image in one step.
....
imgmount c hdd2.img -u
....
This will cause the currently mounted harddisk image (if any) to be unmounted, and hdd2.img to be mounted instead.

Alternatively you can unmount a harddisk image from the DOSBox-X menu bar by selecting "Drive", followed by the drive letter and "Unmount".

## Booting from a harddisk image
First mount the harddisk image, and then boot from it as follows:
....
imgmount c hdd.img
boot c:
....
NOTE: DOSBox-X supports the ``-L`` parameter for the ``BOOT`` command for backward compatibility with vanilla DOSBox, or other forks, but the parameter is not required with DOSBox-X to boot from a drive letter.

## Using harddisk images in Linux
WARNING: You should never mount a harddisk image simultaneously in both DOSBox-X and in Linux, as that can cause corruption of files or the filesystem on the diskette image.

### Gnome Disk Image Mounter
If your using the Gnome desktop environment, you can open .IMG disks with the "Disk Image Mounter".
Simply right click on the file, and select 'Open with Disk Image Mounter' and the file will be mounted in the Gnome file manager.

NOTE: If the harddisk image contains multiple partitions, they will ALL be mounted.

Disks can be unmounted from the Gnome file manager by clicking the unmount button next to the volume name.

Disk images can also be mounted from the Linux Terminal using:
....
gnome-disk-image-mounter hdd.img
....

### Mounting a harddisk image from the shell
The more traditional Linux method of mounting harddisk image files from a Linux terminal. This method requires sudo access.

....
sudo mount -o loop,offset=32256,uid=$UID hdd.img /mnt
....
The above command will cause hdd.img to be mounted under /mnt

The offset is requires to skip the Master Boot Record (MBR) and partition data at the beginning of the harddisk image.

TIP: This command will mount the first partition only.
If the harddisk image contains multiple partitions, you can find the offset for the other partitions by running ``fdisk -l hdd.img`` and looking for the "Start" of the partition, and multiply the value by 512.
For the first partition this should normally always start at 63*512=32256

## Using harddisk images in Windows
Windows 8 and newer has integrated support for mounting image files, and will offer the "Mount" option when you right-click a .IMG file.
Unfortunately this support is incompatible with the image files used by DOSBox-X, and the mount will fail.

One tool which is able to open harddisk images is 7-Zip.

# CD-ROM or DVD images
DOSbox-X supports CD-ROM or DVD image files in ISO9660, CUE/BIN or MDF image format.

ISO9660 (aka ISO) is the easiest format to work with, as long as there is only a single track on the CD or DVD.
If the CD or DVD contains multiple tracks, the use of CUE/BIN or MDF is required.

## Mounting CD or DVD images
Mounting a CD or DVD image in DOSBox-X is typically as simple as

....
imgmount d cdrom.iso
....
This is equivalent to
....
imgmount D: cdrom.iso
imgmount D: cdrom.iso -t iso
imgmount D: cdrom.iso -t cdrom
....
NOTE: The ``-t iso`` or ``-t cdrom`` parameter is only needed with DOSBox-X when the extension is not .ISO, .CUE or .MDF.

### Mounting multiple CD or DVD images
Some DOS programs or games came on multiple CD or DVDs, for this purpose it is possible to mount multiple images on one drive letter and swap between them.
e.g.
....
imgmount d cdrom1.iso cdrom2.iso cdrom3.iso
....
In this example cdrom1.iso will be immediately usable on D: but cdrom2.iso will require a disk-swap action.

Disk-swap can be done using either a hot-key combination, or using the menu bar.
The hot-key for Windows is F11+CTRL+C and for other platforms F12+CTRL+C.
Or from the menu you can select "DOS" followed by "Swap CD".

Unless you have a console open with the log, there is no visual indication of which diskette image is currently mounted.

## Unmounting CD or DVD images
CD or DVD images can be unmounted using the ``-u`` flag. e.g.
....
imgmount d -u
....
You can also unmount using the ``MOUNT`` command.
....
mount d -u
....
It is also possible to unmount the currently mounted image, and mount a new image in one step.
....
imgmount d cdrom2.iso -u
....
This will cause the currently mounted image file (if any) to be unmounted, and cdrom2.iso to be mounted instead.

Alternatively you can unmount a image from the DOSBox-X menu bar by selecting "Drive", followed by the drive letter and "Unmount".

## Boot from a CD or DVD image
DOSBox-X has limited support for booting from a CD or DVD.
Only those that use the El Torito emulated diskette method are supported, such as the Windows 98 or Windows ME full-OEM editions.

You first need to mount the CD-ROM, then mount the diskette image, located on the CD-ROM, and finally you can boot from the A: drive:
....
imgmount d Win98.iso
imgmount 0 -el-torito D -t floppy -fs none
boot A:
....
NOTE: If the second command gives the error "*El Torito boot record not found*", the CD-ROM is either not bootable or uses an unsupported boot method.

NOTE: DOSBox-X supports the ``-L`` parameter for the ``BOOT`` command for backward compatibility with vanilla DOSBox, or other forks, but the parameter is not required with DOSBox-X to boot from a drive letter.

## Using CD or DVD images in Linux
ISO images are fully supported by standard Linux tools, but CUE/BIN and MDF are not.

### Gnome Disk Image Mounter
If your using the Gnome desktop environment, you can open .ISO disks with the "Disk Image Mounter". Simply right click on the file, and select 'Open with Disk Image Mounter' and the file will be mounted in the Gnome file manager.
This method will not work for CUE/BIN or MDF files.

Disks can be unmounted from the Gnome file manager by clicking the unmount button next to the volume name.

ISO images can also be mounted from the Linux Terminal using:
....
gnome-disk-image-mounter cdrom.iso
....

### CDEmu
link:https://cdemu.sourceforge.io/[CDEmu] is a CD-ROM emulator for Linux. It supports numerous image formats, including ISO and CUE/BIN.

### Mounting a ISO image from the shell
The more traditional Linux method of mounting diskette image files from a Linux terminal.
This method will not work for CUE/BIN or MDF files.
This method requires sudo access.

....
sudo mount -o loop cdrom.iso /mnt
....
The above command will cause cdrom.iso to be mounted under /mnt.

## Using CD or DVD images in Windows

Windows 8 and later has integrated support for mounting ISO files. Simply right-click a ISO file and select "Mount".

Alternatively there is link:https://wincdemu.sysprogs.org/[WinCDEmu] which can mount amongst others ISO, CUE/BIN and MDF images.

Programs like 7-Zip, WinRAR and WinZIP can also extract the contents of a ISO file

# Outstanding issues

* For ``IMGMAKE``, what in the IBM PC world uses 10-sector diskettes??
* QCOW2 format, mention it in more detail and also how to use the COW functionality
* source mentions .hdi, .nhd, .nfd, .vhd image files say something about them
* copying files to/from image files from within DOSBox-X using local mounts
* Mention issue with mounting a CD-ROM image from real dos (need driver)
* Mention running ``IMGMOUNT`` or ``MOUNT`` without arguments for list of mounts
* Mention archiving real diskettes
* Mention windows exclusive ``IMGMOUNT`` -source, -r and -bat options.
* ``imgmount --help`` claims you can specify -size and then drivesize in KB. This does not seem to work. Is this only for RAM disks?
* How about -t ram
* how about IDE teriary through octenary controllers in dosbox config. Do the device ID and/or -ide options continue counting up to ID 18 and ``-ide 8s``?
* Accessing harddisk images from Windows? Do the same tools as for diskette images work?
* Accessing image files from MacOS?
* Anything to add for the PC-98?
