:toc: macro

Back to the link:Guide%3AWindows-in-DOSBox‐X[Windows Installation in DOSBox-X]

# Installing Microsoft Windows 98 in DOSBox-X

toc::[]

# Overview
## CD-ROM editions this applies to

* Windows 98 (RTM; Original release)
* Windows 98 Second Edition (98SE)

# DOSBox-X config file
You first need to create a DOSBox-X config file.
....
[dosbox]
title=Windows 98
memsize=64

[cpu]
cputype=pentium_mmx
core=normal

[pci]
# Uncomment the line below if you don't want 3dfx Voodoo support
#voodoo=false

[ne2000]
# If you want networking in Windows, set ne2000=true.
# This also requires that you set realnic= to a suitable value for your PC
ne2000=false
realnic=list

[serial]
# To prevent an IRQ conflict in case you enable NE2000
serial2=disabled

[fdc, primary]
int13fakev86io=true

[ide, primary]
int13fakev86io=true

[ide, secondary]
int13fakev86io=true
cd-rom insertion delay=4000

[render]
scaler=none
aspect=false

[autoexec]
....

Copy the above config and save it as *win98.conf*

*Notes*

* While Windows 98 should support up to 2048MB RAM, memsize=512 is the largest safe value. Larger values may be possible with tweaks, but are not covered here.
* The [autoexec] section will need lines added later.
* If you want networking in Windows, you need to set ne2000=true and change the realnic= value to one suitable for your PC. See:
 link:Guide%3A-Setting-up-networking-in-DOSBox-X[Guide: Setting up networking] for more information.

# Method 1: Boot from CD-ROM image
Starting with Windows 98, it is possible to boot directly from the CD-ROM, as long as you have the "OEM Full" edition, in which case no separate bootdisk is needed.

## Preparing the Harddisk image
First you need to start DOSBox-X from the command-line, using the newly created win98.conf. This assumes that dosbox-x is in your path and win98.conf is in your current directory.
....
dosbox-x -conf win98.conf
....
Then in DOSBox-X you need to create a new harddisk image file, and mount it as drive 2 (IDE primary master). You cannot simply mount it a "C" as the integrated DOS in DOSBox-X has no support for partitions over 2GB, or the FAT32 filesystem.

This FAT32 example uses a 4GB partition. According to Microsoft the official maximum size is 32GB, but in actuality FAT32 can support up to 2TB. However, sizes larger then 128GB are not supported by the generic IDE driver in Windows 98. Larger sizes may be possible with 3rd party drivers, but are not covered here.
....
IMGMAKE hdd.img -t hd_4gig
IMGMOUNT 2 hdd.img -fs none
....
Note: If you create a different sized HDD, pay close attention to the output of IMGMAKE and write down the sectors, heads and cylinders as you will need them to access the harddisk from here on. The IMGMOUNT size parameter should be specified as: -size 512,<sectors>,<heads>,<cylinders>.

== Starting the installation
Now let’s boot from the CD-ROM and start the installation.
....
IMGMOUNT D Win98.iso -t iso
IMGMOUNT 0 -el-torito D -t floppy -fs none
BOOT -L A
....

If the second ```IMGMOUNT``` command gives an error "*El Torito boot record not found*", your CD-ROM image is not bootable, and you will have to use either a different installation method or a different Windows 98 CD-ROM image.

After the first time the Windows installer reboots, your back at the DOSBox-X ```Z:\>``` prompt. Close DOSBox-X and edit your win98.conf config file, and add the following lines in the [autoexec] section at the end of the file:

....
IMGMOUNT 2 hdd.img -fs none
IMGMOUNT D Win98.iso -t iso
BOOT -L C
....

Now start DOSBox-X as follows to continue the installation process:

....
dosbox-x -conf win98.conf
....

## Transfer Windows install files to your HDD image
This is an optional step. It is to prevent Windows from asking for the CD-ROM whenever it needs additional files.

Boot Windows 98 with the CD-ROM image mounted. In Windows 98, copy the \WIN98 directory and its contents from the CD-ROM to your C: drive. You can copy it to any directory you want, but we assume here that you copied it to C:\WIN98

Once the files are copied, start REGEDIT and navigate to ```HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Setup``` and change ```SourcePath=``` to the location where you copied the files. e.g. ```SourcePath=C:\WIN98```

In the case of Windows 98SE, copying the entire directory will require roughly 174MB of diskspace. The \WIN98\OLS and \WIN98\TOUR sub-directories can however be skipped which will save roughly 54MB, bringing the total to roughly 120MB.

# Method 2: Running setup.exe from DOSBox-X
*Notes*

* This method will only allow a primary FAT16 drive of up to 2GB. If you want a larger (FAT32) primary drive, follow the first method.

First you need to start DOSBox-X from the command-line, using the newly created win98.conf. This assumes that dosbox-x is in your path and win98.conf is in your current directory.
....
dosbox-x -conf win98.conf
....
Then in DOSBox-X you need to create a new harddisk image file, and mount it as the C: drive. We use a 2048MB (2GB) HDD for this purpose, as that is the maximum size for FAT16.
....
IMGMAKE hdd.img -t hd_2gig
IMGMOUNT C hdd.img
....

You will also need to mount the Windows 98 CD-ROM. There are a few ways of doing so.

### Mount as ISO image
If you have a copy of the Windows 98 CD-ROM as an ISO (or a cue/bin pair), you can mount it as follows:
....
IMGMOUNT D Win98.iso
....

### Mount as directory
If instead you have the contents of the Windows 98 CD-ROM copied to your harddisk, in a directory 'win98', you can mount it as follows:
....
MOUNT D win98 -t cdrom
....

### Mount from a CD-ROM drive
If your running Windows, you can put the Windows 98 CD-ROM in your CD or DVD drive and directly access it from DOSBox-X. In this example, we assume the optical drive is D: on your windows installation, and your also mounting it as D: in DOSBox-X.

....
MOUNT D D:\ -t cdrom
....

## Copying the contents of the CD-ROM
While not strictly necessary, as it is possible to run SETUP.EXE directly from the CD-ROM (as long as you have the CD-ROM automatically mounted in your [autoexec] section of the config file), it is recommended to copy the installation files (contents of the WIN98 directory on the CD-ROM) to your HDD image, as it will prevent Windows 98 from asking for the CD-ROM when it needs additional files later.

....
XCOPY D:\WIN98 C:\WIN98 /I /E
....

## Running SETUP.EXE
You can now run SETUP.EXE, but it need to be started with the ```/IS``` parameter to disable the ScanDisk function as it will otherwise fail to successfully scan the DOSBox-X Z: drive.

....
C:
CD \WIN98
SETUP /IS
....

Now run through the install process, until it reboots and your back at the DOSBox-X ```Z:\``` prompt. At this point close DOSBox-X, and edit your win98.conf config file. At the end of the file, in the [autoexec] section, add the following two lines:

....
IMGMOUNT C hdd.img
BOOT -L C
....

Save the config file, and at the command-prompt you can type the following to continue the installation process. This is also the command you use, after the installation is finished, to start Windows 98 in DOSBox-X.

....
dosbox-x -conf win98.conf
....

# Method 3: Booting from a DOS bootdisk
If none of the installation options are suitable, you can boot from a Windows 98 or DOS 5.0 (or later) boot disk. This process is described on the link:Guide%3A-Installing-Windows-95-in-DOSBox-X[Windows 95 installation page] and will not be duplicated here.

# General installation Notes

* Some parts of the installation can take a considerable amount of time. You can speed this up somewhat by using the DOSBox-X Turbo mode by either pressing Alt-F12, or from the drop-down menu select "CPU" followed by "Turbo (Fast Forward)". But if you decide to use this, be sure to disable Turbo mode whenever you need to enter data or make choices, as it can cause spurious key-presses to be registered causing undesirable effects.
* When creating your HDD image with ```IMGMAKE```, instead of specifying a custom size, you can choose a pre-defined template. The advantage of using a pre-defined template in combination with an unsupported partition layout or filesystem (e.g. FAT32) is that you don't have to specify the sector-size, sectors, heads and cylinders each time you mount the HDD. The pre-defined HDD templates can be seen by running ```IMGMAKE``` without arguments.
** Example: If you create a custom 4GB size HDD image:
*** ```IMGMAKE hdd.img -t hd -size 4096 -nofs```
*** ```MOUNT 2 hdd.img -size 512,63,130,1023 -fs none```
** Example: If using a pre-defined HDD template:
*** ```IMGMAKE hdd.img -t hd_4gig -nofs```
*** ```MOUNT 2 hdd.img -fs none```
* During the installation it may ask you if you have a CD-ROM, Network card or sound card that you want it to scan for. You may want to select to scan for a soundcard, as otherwise it may not detect your soundcard (sometimes it does, sometimes it doesn't). Likewise, if you have NE2000 enabled in your DOSBox-X config file, you may also want to check the Network adapter box. Your DOSBox-X CD-ROM will be detected regardless if you check it's box or not.

# Booting Windows 98 after installation
After the installation is finished, you can start Windows 98 from the command-prompt with the following command:

....
dosbox-x -conf win98.conf
....

# Steps to take after Installation
Once Windows 98 is installed, here is some additional software you may want to install or update:

* Microsoft .NET framework version 1.0, 1.1 and 2.0
* Visual C++ 2005 runtime
* Update to Internet Explorer 6.0 (rarely needed)
* Update to DirectX 9.0c
* Windows Installer 2.0
* Install WinG 1.0 (needed by just a few games, and those games typically include it)
* GDI+ redistributable

link:https://msfn.org/board/topic/105936-last-versions-of-software-for-windows-98se/[Forum thread about: Last Versions of Software for Windows 98SE]

# Enabling networking
If you enabled NE2000 support in the DOSBox-X config file, and Windows 98 did not detect the adapter, go to "Start", "Settings" and "Control Panel" and double-click on "Add New Hardware", and let the wizard detect hardware. It should find the NE2000 adapter and install the drivers.

By default it will try to get it's network configuration over DHCP, if you need to manually specify the settings, in "Control Panel", double-click "Network". Once it opens, highlight "TCP/IP", and click the "Properties" button to modify the TCP/IP settings.

In the Network settings, there may also be a "Dial-Up Adapter" listed, which you can safely delete.

# Enabling sound
The Windows 98 installer does not always detect the presence of a sound card, as the emulated soundcard in DOSBox-X does not support PnP. If you do not have sound support, go to "Start", "Settings" and "Control Panel" and double-click on "Add New Hardware". Now simply follow the guide and let it install support for any devices that it detects.
