:toc: macro

Back to the link:Home[DOSBox-X Wiki Welcome page].

# Regional settings in DOSBox-X

toc::[]

### Overview

You can customize the regional settings in DOSBox-X, such as changing the international keyboard layouts and
codepages, as well as changing the country code for country-specific date/time formats. Both can be done either
from the DOSBox-x config file (dosbox-x.conf by default), or from the DOSBox-X command line.

### International keyboard layouts and codepages

The US keyboard layout is used by default in DOSBox-X. DOSBox-X was developed around this keyboard layout just like
DOSBox, which DOSBox-X is based on. This is primarily due to limitations around the SDL1 (SDL 1.2.x) library. SDL
is responsible for input handling, and SDL1 in particular only supports US keyboards. As such when using the SDL1
version and a non-US keyboard, DOSBox-X will automatically use scancodes with the default ``usescancodes=auto``
config setting to work around keyboard layout problems.

When using the SDL2 binary, scancodes are not needed when using non-US keyboard layouts.

When starting DOSBox-X on a Windows system with the default ``keyboardlayout=auto`` config setting, it will try to
set the keyboard layout automatically, depending on the host OS region, for a wide range of regions. This may not
necessarily match your actual keyboard, or your region may not currently be supported. In addition, the ``auto``
setting has no effect on Linux and MacOS.

You can set your keyboard layout manually in the [dos] section of the dosbox-x.conf file. For instance to set a
German keyboard layout you can specify ``keyboardlayout=de``. It will also automatically set a suitable codepage. 

Alternatively, the KEYB command can be used from the DOSBox-X command line to change the keyboard layout.
For example:

``KEYB UK``

This command will switch the current keyboard layout to the UK keyboard layout and set code page 858.

Alternatively you can also specify a different codepage by adding the codepage number to the end.

``KEYB UK 850``

Most Western-European countries would have used codepage 850 back in the day, but DOSBox-X by
default uses codepage 858, which is the same as codepage 850 with the addition of the Euro symbol.

Note that software that uses certain box drawing characters may not look 100% accurate unless codepage 437
(default US codepage) is used. But this codepage lacks many diacritic glyphs that may be needed for regional
support. As such a choice may have to be made between support for those box drawing characters or diacritic glyphs.

The Japanese keyboard layout is also supported in NEC PC-98 mode. You can start DOSBox-X in PC-98 mode directly
by setting "machine=pc98" in the [dosbox] section of the dosbox-x.conf file.

If you find that a keyboard layout is not yet supported by DOSBox-X, in order to add additional layouts for use
with DOSBox-X, please see the https://github.com/joncampbell123/dosbox-x/blob/master/README.keyboard-layout-handling[keyboard layout handling page] on how to do so as a developer.

### Country-specific date/time formats

Regional settings can be set in the [config] section of the DOSBox-x config file by use of the ``COUNTRY=``
setting. This defaults to 1, which is the US. This setting influences date and time format as used by DOSBox-X,
such as the ``DIR`` command. It may also influence regional settings in other applications.

For example, the date is displayed in MM/DD/YYYY format with the default US setting:

``30-07-2020 12:34p``

If you change the ``COUNTRY=`` setting, the date and time will be displayed in the format associated with the
specified country code. For example, 44 (or 044) is the country code for the UK, and setting the following:

``COUNTRY=44``

Will cause DOSBox-X to use the UK date and time format:

``07/30/2020 12:34``

You can also instruct DOSBox-X to use the Canadian French date and time format like this: 

``COUNTRY=2``

Then the date and time will be displayed like this:

``2002-07-30 12:34``

A list of country codes and the corresponding date/time formats can be found at http://info.wsisiz.edu.pl/~bse26236/batutil/help/COUNTRN.HTM[MS-DOS COUNTRY Notes].

If you set "COUNTRY=0" in the [config] section of the DOSBox-x config file, then DOSBox-X will try to auto-detect and set the country code based on the system regional setting. This however only works on Windows systems.

Alternatively, the COUNTRY command can be used from the DOSBox-X command line to change the country code, such as ``COUNTRY 61`` for international English. Typing COUNTRY without parameters will display the current country code.