:toc: macro

ifdef::env-github[:suffixappend:]
ifndef::env-github[:suffixappend:]

Back to the link:Home{suffixappend}[DOSBox-X Wiki Welcome page].

# PC-98 emulation in DOSBox-X

toc::[]

As DOSBox-X aims to be complete DOS emulation package, it officially supports the emulations of the PC-98 system. The NEC PC-9800, also known as the PC-98, were a family of computers made by NEC and sold in Japan throughout 1982 to 2000. Most of the PC-98 software are games, but there are also non-gaming PC-98 applications such as the PC-98 version of Windows 3.1. While these were originally designed for Japanese markets, international users who are influenced by the Japanese culture may also want to check this out. For example, earlier Touhou games are PC-98 games, which are well supported by DOSBox-X's PC-98 system.

## Start PC-98 emulation

By default, DOSBox-X starts the standard IBM-compatible DOS system. But you can specify a different system to start with the "machine" config in DOSBox-X's configuration file (dosbox-x.conf by default), which offers system types including PC-98. So if you set "machine" to "pc98" (or "pc9801"/"pc9821" which are synonyms for "pc98" at this time), then DOSBox-X will start in the PC-98 emulation mode. Alternative you can specify the PC-98 machine type directly at the DOSBox-X command line, such as ```dosbox-x -set machine=pc98```, which will also start DOSBox-X in the PC-98 emulation mode regardless of the settings in the DOSBox-X config file.

## PC-98 accessory files

You can start DOSBox-X in PC-98 mode without any additional files apart from the DOSBox-X executable itself. However, in order for DOSBox-X to display Japanese texts correctly you will need additional files. It is recommended to have the ``FREECG98.BMP`` file and/or the ``FONT.ROM`` file located in the DOSBox-X directory, then DOSBox-X will be able to display Japanese texts in the standard PC-98 mode:

FREECG98.BMP: https://github.com/joncampbell123/dosbox-x/blob/master/contrib/fonts/FREECG98.BMP?raw=true[Download here]

FONT.ROM: https://retro-type.com/PC98/files/BIOS/PC98Ce2-model-S2D-Bios/Backup-of-Ce2-Bios/Backup-of-Ce2-Bios/Extracted%20Bios%20Files/PC9821-Ce2-S2D-Bios-MKBIOS/FONT.ROM[Download here]

If you want to use the TrueType font (TTF) output option (i.e. with "output=ttf"), then you will need a Japanese monospaced TrueType font for PC-98 mode. For example, you can use any of the Japanese TrueType fonts from the Migu or M+P families:

Migu 1M Regular: https://github.com/chrissimpkins/codeface/blob/master/cjk-fonts/migu1m/migu-1m-regular.ttf?raw=true[Download here]

Migu 2M Regular: https://github.com/chrissimpkins/codeface/blob/master/cjk-fonts/migu2m/migu-2m-regular.ttf?raw=true[Download here]

M+ P Type-1 Regular: https://github.com/chrissimpkins/codeface/blob/master/cjk-fonts/mplus1m/mplus-1m-regular.ttf?raw=true[Download here]

M+ P Type-2 Regular: https://github.com/chrissimpkins/codeface/blob/master/cjk-fonts/mplus1m/mplus-2m-regular.ttf?raw=true[Download here]

In addition, the ``SOUND.ROM`` file is the ROM image of the PC-98 FM board, which may be required by some PC-98 games to make music and sound effects:

SOUND.ROM: https://retro-type.com/PC98/files/BIOS/PC98Ce2-model-S2D-Bios/Backup-of-Ce2-Bios/Backup-of-Ce2-Bios/Extracted%20Bios%20Files/PC9821-Ce2-S2D-Bios-MKBIOS/SOUND.ROM[Download here]