:toc: macro

Back to the link:Home[DOSBox-X Wiki Welcome page]

# Setting up a Joystick in DOSBox-X

toc::[]

# Overview
While game consoles and most home-computers back in the day had two or more Joystick ports, the IBM PC and its clones had none.
IBM did provide a DA-15 game-port adapter option, but few people had it, or a matching PC compatible Joystick.
As such most PC games are designed to be played with the keyboard, or for later games with the mouse.

The IBM game port, just the the PC, was cloned and found its way onto multi-IO cards and soundcards of the era.
But even if PCs had a game port, few owned a matching joystick.
And even nowadays games on the PC are often played with a keyboard and mouse.

This is also reflected in most DOS games.
Joystick support is not universal, and even if the game supports a joystick, the game often has to be specifically configured for it.

The game port's DA-15 connector includes inputs for a total of four analogue channels and four buttons.
These were almost always implemented as two joysticks with two buttons each.
To connect two joysticks to one port, a separate Y-splitter cable was needed.

DOSBox-X uses SDL for input, which includes gamepads. Any SDL supported gamepads will automatically become available within DOSBox-X as a joystick.

For games that do not support Joysticks natively, DOSBox-X provides the possibility to map joystick inputs to keyboard presses.

# DOSBox-X config settings

This section will list the available configuration options that DOSBox-X provides that are relevant to joysticks.

## [joystick] options

### joystick_type
* Default value: auto
* Possible values: auto, none, 2axis, 2axis_2, fcs, ch

NOTE: If changing this setting, or if you saved the mapperfile without joystick connected or with a different joystick, remember to reset dosbox's mapperfile. Otherwise the new setting will not work properly (or at all).

#### 2axis
With this option, you can have two joysticks, but each joystick will only have two axis and two trigger buttons.
Most PC games with joystick support are compatible with this mode.

With a modern gamepad, the two axis will be mapped to the left analogue stick.
And the trigger buttons to two of the face buttons.

#### 4axis
With this option, you can only have a single joystick, but the joystick will have four axis and four trigger buttons.
Alternatively, depending on the gamepad, you can also have two axis, and six trigger buttons.

Few PC games really support more than 2 axis and 2 trigger buttons. But this mode is compatible with those games.

With a modern gamepad, the axis will be mapped to both the left and right analogue sticks.
And the trigger buttons to the four face buttons.

#### 4axis_2
Same as the 4axis option, but as the second joystick.

#### fcs
Emulate a legacy Thrustmaster FCS (Flight Control Stick).

Only select this option, if the game specifically supports this joystick.

Only supports one controller, with 3-axes, 4 buttons and 1 hat.

#### ch
Emulate a legacy CH Flightstick.

Only select this option, if the game specifically supports this joystick.

Only supports one controller, with 4-axes, 6 buttons and 1 hat. But you cannot press more than one button at the same time.

#### none
Disables joystick emulation.

#### auto
Chooses emulation depending on real joystick(s).

If only a single gamepad is detected, it will be set to 4axis.
While if two gamepads are detected, it will be set to 2axis.

### timed
* Default value: true
* Possible values: true, false

Enable timed intervals for axis. Experiment with this option, if your joystick drifts (away) or does not calibrate properly inside DOSBox-X, while it works fine outside DOSBox-X.

### autofire
* Default value: false
* Possible values: true, false

Continuously fires as long as you keep the button pressed.

### swap34
* Default value: false
* Possible values: true, false

Swap the 3rd and the 4th axis. can be useful for certain joysticks.

### buttonwrap
* Default value: false
* Possible values: true, false

Enable button wrapping at the number of emulated buttons.

### joy1deadzone1
* Default value: 0.25
* Possible values:

Deadzone for joystick 1, thumbstick 1.

### joy1deadzone2
* Default value: 0.25
* Possible values:

Deadzone for joystick 1, thumbstick 2.
Only applicable if emulating a joystick with more than 2 axis.

### joy2deadzone1
* Default value: 0.25
* Possible values:

Deadzone for joystick 2, thumbstick 1.
Only applicable if two joysticks are attached, and set to 2axis mode.

### joy1response1
* Default value: 1.00
* Possible values:

Response for joystick 1, thumbstick 1.

### joy1response2
* Default value: 1.00
* Possible values:

Response for joystick 1, thumbstick 2.
Only applicable if emulating a joystick with more than 2 axis.

### joy2response1
* Default value: 1.00
* Possible values:

Response for joystick 2, thumbstick 1.
Only applicable if two joysticks are attached, and set to 2axis mode.

### joy1axis0
* Default value: 0
* Possible values: 0-7

Axis for joystick 1, axis 0.

This allows to remap the axis analogue controls.
For instance if you want to use the right analogue stick, instead of the left.

### joy1axis1
* Default value: 1
* Possible values: 0-7

Axis for joystick 1, axis 1.

### joy1axis2
* Default value: 2
* Possible values: 0-7

Axis for joystick 1, axis 2.

### joy1axis3
* Default value: 3
* Possible values: 0-7

Axis for joystick 1, axis 3.

### joy1axis4
* Default value: 4
* Possible values: 0-7

Axis for joystick 1, axis 4.

### joy1axis5
* Default value: 5
* Possible values: 0-7

Axis for joystick 1, axis 5.
Only applicable if emulating a joystick with more than 2 axis.

### joy1axis6
* Default value: 6
* Possible values: 0-7

Axis for joystick 1, axis 6.
Only applicable if emulating a joystick with more than 2 axis.

### joy1axis7
* Default value: 7
* Possible values: 0-7

Axis for joystick 1, axis 7.
Only applicable if emulating a joystick with more than 2 axis.

### joy2axis0
* Default value: 0
* Possible values: 0-7

Axis for joystick 2, axis 0.
Or if using 4axix_2 mode.

### joy2axis1
* Default value: 1
* Possible values: 0-7

Axis for joystick 2, axis 1.
Only applicable if two joysticks are attached, and set to 2axis mode.
Or if using 4axix_2 mode.

### joy2axis2
* Default value: 2
* Possible values: 0-7

Axis for joystick 2, axis 2.
Only applicable if two joysticks are attached, and set to 2axis mode.
Or if using 4axix_2 mode.

### joy2axis3
* Default value: 3
* Possible values: 0-7

Axis for joystick 2, axis 3.
Only applicable if two joysticks are attached, and set to 2axis mode.
Or if using 4axix_2 mode.

### joy2axis4
* Default value: 4
* Possible values: 0-7

Axis for joystick 2, axis 4.
Only applicable if using 4axix_2 mode.

### joy2axis5
* Default value: 5
* Possible values: 0-7

Axis for joystick 2, axis 5.
Only applicable if using 4axix_2 mode.

### joy2axis6
* Default value: 6
* Possible values: 0-7

Axis for joystick 2, axis 6.
Only applicable if using 4axix_2 mode.

### joy2axis7
* Default value: 7
* Possible values: 0-7

Axis for joystick 2, axis 7.
Only applicable if using 4axix_2 mode.

## [mapper] options
When using the mapper to map gamepad inputs to keyboard presses, additional deadzone options are offered.

### joy1deadzone0-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 0-

### joy1deadzone0+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 0+

### joy1deadzone1-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 1-

### joy1deadzone1+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 1+

### joy1deadzone2-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 2-

### joy1deadzone2+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 2+

### joy1deadzone3-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 3-

### joy1deadzone3+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 3+

### joy1deadzone4-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 4-

### joy1deadzone4+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 4+

### joy1deadzone5-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 5-

### joy1deadzone5+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 5+

### joy1deadzone6-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 6-

### joy1deadzone6+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 6+

### joy1deadzone7-
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 7-

### joy1deadzone7+
* Default value: 0.60
* Possible values:

Deadzone for joystick 1, axis 7+

### joy2deadzone0-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 0-

### joy2deadzone0+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 0+

### joy2deadzone1-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 1-

### joy2deadzone1+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 1+

### joy2deadzone2-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 2-

### joy2deadzone2+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 2+

### joy2deadzone3-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 3-

### joy2deadzone3+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 3+

### joy2deadzone4-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 4-

### joy2deadzone4+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 4+

### joy2deadzone5-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 5-

### joy2deadzone5+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 5+

### joy2deadzone6-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 6-

### joy2deadzone6+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 6+

### joy2deadzone7-
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 7-

### joy2deadzone7+
* Default value: 0.60
* Possible values:

Deadzone for joystick 2, axis 7+
